/*

------DESCRIZIONE STEP ESERCIZI-----

1)  GENERARE ARRAY DI NUMERI CASUALI E INSERIRLI NEL DOM
2)  IMPOSTARE TIMER DI 30 SECONDI PER FARLI SPARIRE
3)  TRAMITE PROMPT FARE INSERIRE I NUMERI ALL'UTENTE E SALVARLI IN UN ALTRO ARRAY
4)  CONTROLLARE SE I NUMERI DELL'ARRAY UTENTE SONO CONTENUTI NELL'ARRAY DI NUMERI GENERATI ALL'INIZIO
5)  CREARE UN ARRAY CON I NUMERI CHE SONO UGUALI
6)  MOSTRARE ARRAY DI NUMERI INDOVINATI DALL'UTENTE E NUMERO DI ELEMENTI NELL'ARRAY


 */